// Code generated by MockGen. DO NOT EDIT.
// Source: productGofr/services (interfaces: Iservice)

// Package services is a generated GoMock package.
package services

import (
	models "productGofr/models"
	reflect "reflect"

	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
)

// MockIservice is a mock of Iservice interface.
type MockIservice struct {
	ctrl     *gomock.Controller
	recorder *MockIserviceMockRecorder
}

// MockIserviceMockRecorder is the mock recorder for MockIservice.
type MockIserviceMockRecorder struct {
	mock *MockIservice
}

// NewMockIservice creates a new mock instance.
func NewMockIservice(ctrl *gomock.Controller) *MockIservice {
	mock := &MockIservice{ctrl: ctrl}
	mock.recorder = &MockIserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIservice) EXPECT() *MockIserviceMockRecorder {
	return m.recorder
}

// GetProductById mocks base method.
func (m *MockIservice) GetProductById(arg0 *gofr.Context, arg1 string) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductById", arg0, arg1)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductById indicates an expected call of GetProductById.
func (mr *MockIserviceMockRecorder) GetProductById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductById", reflect.TypeOf((*MockIservice)(nil).GetProductById), arg0, arg1)
}
